[profile.default]
auto_detect_solc = false
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"
remappings = [
    'forge-std/=lib/forge-std/src/',
    'src/=src/',
    'openzeppelin/=lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'semaphore/=lib/semaphore/packages/contracts/contracts/',
    'poseidon-solidity/=lib/poseidon-solidity/contracts/',
    '@zk-kit/=lib/zk-kit/packages/'
]



# See more config options https://github.com/foundry-rs/foundry/tree/master/config